# Generated by Django 5.2.1 on 2025-05-15 10:50

from django.db import migrations

def create_categories(apps, schema_editor):
    Category = apps.get_model('base', 'Category')
    default_categories = ['Top', 'Bottom', 'Shoe', 'Accessory', 'Hat']

    existing = set(Category.objects.all().values_list('name', flat=True))
    for name in default_categories:
        if name not in existing:
            Category.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
