# Generated by Django 5.2 on 2025-05-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_outfit'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
